### PR TITLE
fix: Fix `index` slug value

### PR DESCRIPTION
**Pull request by mrousavy**
This fixes the `index.md`'s `slug` value.

Without this change, docususaurus complains about broken links:

```
Info: Documentation generated at ./docs/api

✔ Client
  

● Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 stored

Unable to build website for locale "en".
Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /react-native-vision-camera/docs/api:
   -> linking to classes/Camera (resolved as: /react-native-vision-camera/docs/classes/Camera)
   -> linking to classes/CameraCaptureError (resolved as: /react-native-vision-camera/docs/classes/CameraCaptureError)
   -> linking to classes/CameraRuntimeError (resolved as: /react-native-vision-camera/docs/classes/CameraRuntimeError)
   -> linking to interfaces/CameraDevice (resolved as: /react-native-vision-camera/docs/interfaces/CameraDevice)
   -> linking to interfaces/CameraDeviceFormat (resolved as: /react-native-vision-camera/docs/interfaces/CameraDeviceFormat)
   -> linking to interfaces/CameraProps (resolved as: /react-native-vision-camera/docs/interfaces/CameraProps)
   -> linking to interfaces/ErrorWithCause (resolved as: /react-native-vision-camera/docs/interfaces/ErrorWithCause)
   -> linking to interfaces/Frame (resolved as: /react-native-vision-camera/docs/interfaces/Frame)
   -> linking to interfaces/FrameProcessorPerformanceSuggestion (resolved as: /react-native-vision-camera/docs/interfaces/FrameProcessorPerformanceSuggestion)
   -> linking to interfaces/FrameRateRange (resolved as: /react-native-vision-camera/docs/interfaces/FrameRateRange)
   -> linking to interfaces/PhotoFile (resolved as: /react-native-vision-camera/docs/interfaces/PhotoFile)
   -> linking to interfaces/Point (resolved as: /react-native-vision-camera/docs/interfaces/Point)
   -> linking to interfaces/RecordVideoOptions (resolved as: /react-native-vision-camera/docs/interfaces/RecordVideoOptions)
   -> linking to interfaces/TakePhotoOptions (resolved as: /react-native-vision-camera/docs/interfaces/TakePhotoOptions)
   -> linking to interfaces/TakeSnapshotOptions (resolved as: /react-native-vision-camera/docs/interfaces/TakeSnapshotOptions)
   -> linking to interfaces/TemporaryFile (resolved as: /react-native-vision-camera/docs/interfaces/TemporaryFile)
   -> linking to interfaces/VideoFile (resolved as: /react-native-vision-camera/docs/interfaces/VideoFile)
   -> linking to index#physicalcameradevicetype (resolved as: /react-native-vision-camera/docs/index)
   -> linking to index#logicalcameradevicetype (resolved as: /react-native-vision-camera/docs/index)

- On source page path = /react-native-vision-camera/docs/api/classes/Camera:
   -> linking to ../index#usecameradevices (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#camerapermissionstatus (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#camerapermissionrequestresult (resolved as: /react-native-vision-camera/docs/api/index)

- On source page path = /react-native-vision-camera/docs/api/classes/CameraCaptureError:
   -> linking to ../index#captureerror (resolved as: /react-native-vision-camera/docs/api/index)

- On source page path = /react-native-vision-camera/docs/api/classes/CameraRuntimeError:
   -> linking to ../index#permissionerror (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#parametererror (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#deviceerror (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#formaterror (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#sessionerror (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#systemerror (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#unknownerror (resolved as: /react-native-vision-camera/docs/api/index)

- On source page path = /react-native-vision-camera/docs/api/interfaces/CameraDevice:
   -> linking to ../index#physicalcameradevicetype (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#cameraposition (resolved as: /react-native-vision-camera/docs/api/index)

- On source page path = /react-native-vision-camera/docs/api/interfaces/CameraDeviceFormat:
   -> linking to ../index#autofocussystem (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#colorspace (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#videostabilizationmode (resolved as: /react-native-vision-camera/docs/api/index)

- On source page path = /react-native-vision-camera/docs/api/interfaces/CameraProps:
   -> linking to ../index#colorspace (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#camerapreset (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#videostabilizationmode (resolved as: /react-native-vision-camera/docs/api/index)

- On source page path = /react-native-vision-camera/docs/api/interfaces/RecordVideoOptions:
   -> linking to ../index#videofiletype (resolved as: /react-native-vision-camera/docs/api/index)

    at Object.reportMessage (/Users/mrousavy/Projects/react-native-vision-camera/docs/node_modules/@docusaurus/utils/lib/index.js:308:19)
    at Object.handleBrokenLinks (/Users/mrousavy/Projects/react-native-vision-camera/docs/node_modules/@docusaurus/core/lib/server/brokenLinks.js:142:17)
    at async buildLocale (/Users/mrousavy/Projects/react-native-vision-camera/docs/node_modules/@docusaurus/core/lib/commands/build.js:160:5)
    at async tryToBuildLocale (/Users/mrousavy/Projects/react-native-vision-camera/docs/node_modules/@docusaurus/core/lib/commands/build.js:32:20)
    at async Object.mapAsyncSequencial (/Users/mrousavy/Projects/react-native-vision-camera/docs/node_modules/@docusaurus/utils/lib/index.js:263:24)
    at async build (/Users/mrousavy/Projects/react-native-vision-camera/docs/node_modules/@docusaurus/core/lib/commands/build.js:68:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

With this change the build works fine and no broken links are detected.

You can reproduce the error above by cloning [mrousavy/react-native-vision-camera](https://github.com/mrousavy/react-native-vision-camera), switching to [the `chore/upgrade-dependencies` branch](https://github.com/mrousavy/react-native-vision-camera/tree/chore/upgrade-dependencies), and then running the following commands:

```
yarn
yarn build
```

### CODE REVIEW

**Comment by mrousavy** [comment]
Here's a copy and pasteable script to reproduce the error I'm experiencing without my change:

```bash
cd /tmp

git clone https://github.com/mrousavy/react-native-vision-camera

cd react-native-vision-camera
git checkout chore/upgrade-dependencies

cd docs
yarn
yarn start
```

When I change `docs/docs/api/index.md`'s `slug` from `/api` -> `/api/index` everything works fine. Let me know if my PR is the right way to solve this or not.

**Comment by mrousavy** [comment]
Hey @tgreyuk, thanks for merging! Can you confirm on your end that my change fixes this issue? I hope the change is not bulls*it 😄

**Comment by tgreyuk** [comment]
hi @mrousavy it seemed reasonably by looking at it but will have a proper check before releasing anything as to what the impact is (i prob should have checked first before merging but crazy busy at moment :0). thanks by the way any contributions / suggestions welcome.

**Comment by tgreyuk** [comment]
@mrousavy the actual issue was that relative urls to the slug page were broken, so fixed that rather than changing the slug. should be fixed in docusaurus-plugin-typedoc@0.16.1

**Comment by mrousavy** [comment]
Hmm, the build still doesn't work for me:

```
Unable to build website for locale "en".
Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /react-native-vision-camera/docs/api:
   -> linking to classes/Camera (resolved as: /react-native-vision-camera/docs/classes/Camera)
   -> linking to classes/CameraCaptureError (resolved as: /react-native-vision-camera/docs/classes/CameraCaptureError)
   -> linking to classes/CameraRuntimeError (resolved as: /react-native-vision-camera/docs/classes/CameraRuntimeError)
   -> linking to interfaces/CameraDevice (resolved as: /react-native-vision-camera/docs/interfaces/CameraDevice)
   -> linking to interfaces/CameraDeviceFormat (resolved as: /react-native-vision-camera/docs/interfaces/CameraDeviceFormat)
   -> linking to interfaces/CameraProps (resolved as: /react-native-vision-camera/docs/interfaces/CameraProps)
   -> linking to interfaces/ErrorWithCause (resolved as: /react-native-vision-camera/docs/interfaces/ErrorWithCause)
   -> linking to interfaces/Frame (resolved as: /react-native-vision-camera/docs/interfaces/Frame)
   -> linking to interfaces/FrameProcessorPerformanceSuggestion (resolved as: /react-native-vision-camera/docs/interfaces/FrameProcessorPerformanceSuggestion)
   -> linking to interfaces/FrameRateRange (resolved as: /react-native-vision-camera/docs/interfaces/FrameRateRange)
   -> linking to interfaces/PhotoFile (resolved as: /react-native-vision-camera/docs/interfaces/PhotoFile)
   -> linking to interfaces/Point (resolved as: /react-native-vision-camera/docs/interfaces/Point)
   -> linking to interfaces/RecordVideoOptions (resolved as: /react-native-vision-camera/docs/interfaces/RecordVideoOptions)
   -> linking to interfaces/TakePhotoOptions (resolved as: /react-native-vision-camera/docs/interfaces/TakePhotoOptions)
   -> linking to interfaces/TakeSnapshotOptions (resolved as: /react-native-vision-camera/docs/interfaces/TakeSnapshotOptions)
   -> linking to interfaces/TemporaryFile (resolved as: /react-native-vision-camera/docs/interfaces/TemporaryFile)
   -> linking to interfaces/VideoFile (resolved as: /react-native-vision-camera/docs/interfaces/VideoFile)
   -> linking to index#physicalcameradevicetype (resolved as: /react-native-vision-camera/docs/index)
   -> linking to index#logicalcameradevicetype (resolved as: /react-native-vision-camera/docs/index)

- On source page path = /react-native-vision-camera/docs/api/classes/Camera:
   -> linking to ../index#usecameradevices (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#camerapermissionstatus (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#camerapermissionrequestresult (resolved as: /react-native-vision-camera/docs/api/index)

- On source page path = /react-native-vision-camera/docs/api/classes/CameraCaptureError:
   -> linking to ../index#captureerror (resolved as: /react-native-vision-camera/docs/api/index)

- On source page path = /react-native-vision-camera/docs/api/classes/CameraRuntimeError:
   -> linking to ../index#permissionerror (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#parametererror (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#deviceerror (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#formaterror (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#sessionerror (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#systemerror (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#unknownerror (resolved as: /react-native-vision-camera/docs/api/index)

- On source page path = /react-native-vision-camera/docs/api/interfaces/CameraDevice:
   -> linking to ../index#physicalcameradevicetype (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#cameraposition (resolved as: /react-native-vision-camera/docs/api/index)

- On source page path = /react-native-vision-camera/docs/api/interfaces/CameraDeviceFormat:
   -> linking to ../index#autofocussystem (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#colorspace (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#videostabilizationmode (resolved as: /react-native-vision-camera/docs/api/index)

- On source page path = /react-native-vision-camera/docs/api/interfaces/CameraProps:
   -> linking to ../index#colorspace (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#camerapreset (resolved as: /react-native-vision-camera/docs/api/index)
   -> linking to ../index#videostabilizationmode (resolved as: /react-native-vision-camera/docs/api/index)

- On source page path = /react-native-vision-camera/docs/api/interfaces/RecordVideoOptions:
   -> linking to ../index#videofiletype (resolved as: /react-native-vision-camera/docs/api/index)

    at Object.reportMessage (/Users/mrousavy/Projects/react-native-vision-camera/docs/node_modules/@docusaurus/utils/lib/index.js:308:19)
    at Object.handleBrokenLinks (/Users/mrousavy/Projects/react-native-vision-camera/docs/node_modules/@docusaurus/core/lib/server/brokenLinks.js:142:17)
    at async buildLocale (/Users/mrousavy/Projects/react-native-vision-camera/docs/node_modules/@docusaurus/core/lib/commands/build.js:160:5)
    at async tryToBuildLocale (/Users/mrousavy/Projects/react-native-vision-camera/docs/node_modules/@docusaurus/core/lib/commands/build.js:32:20)
    at async Object.mapAsyncSequencial (/Users/mrousavy/Projects/react-native-vision-camera/docs/node_modules/@docusaurus/utils/lib/index.js:263:24)
    at async build (/Users/mrousavy/Projects/react-native-vision-camera/docs/node_modules/@docusaurus/core/lib/commands/build.js:68:25)
```

(Reproduceable example still same, [here](https://github.com/mrousavy/react-native-vision-camera/tree/chore/upgrade-dependencies)'s the link and commands to get it running are above)

**Comment by mrousavy** [comment]
Let's take a look at the individual lines:

```
   -> linking to classes/Camera (resolved as: /react-native-vision-camera/docs/classes/Camera)
```

this should be `/react-native-vision-camera/docs/api/classes/Camera` instead.


but this:

```
   -> linking to ../index#permissionerror (resolved as: /react-native-vision-camera/docs/api/index)
```

seems to me like it would be correct, no? 🤔

**Comment by tgreyuk** [comment]
I have tested on your branch with 0.16.1. there were build errors on the first run but then was successful on the 2nd build onwards. not quite sure why!

**Comment by tgreyuk** [comment]
Please try with 0.16.2.. hopefully fix your issue.

**Comment by mrousavy** [comment]
Hi @tgreyuk, thank you for your patience and help, but unfortunately it still doesn't build for me on 0.16.2. I'm thinking if I have misconfigured something?

**Comment by tgreyuk** [comment]
@mrousavy very sorry about this. I have tested your repo on 0.16.3 and it is building ok for me. can you please confirm? if not its back to the drawing board!!

**Comment by mrousavy** [comment]
Thank you so much for your time. You're amazing. It works with `0.16.3`. ❤️

**Pull request merged**
