### PR TITLE
Feature: (docusaurus) autogenerated sidebars

### PR DESCRIPTION
**Pull request by tgreyuk**
## Motivation

With the introduction of autogenerated sidebars in Docusaurus 2.0.0-alpha73 (https://github.com/facebook/docusaurus/pull/4582) manual sidebar generation is no longer required (or desired): 

Default usage:

```
// sidebars.js
module.exports = {
  someSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the docs folder
    },
  ],
};
```

Slice usage:

```
// sidebars.js
module.exports = {
  someSidebar: {
    'Category 1': ['doc1', 'doc2', 'doc3'],
    'API': [
      {
        type: 'autogenerated',
        dirName: 'api', // 'api' is the 'out' directory
      },
    ],
  },
};
```

Additional options (not relevant if using a sidebar slice):

- `sidebar.categoryLabel` The sidebar parent category label.
- `sidebar.position` The position of the sidebar in the tree.

Other notes:

- Readme and globals/TOC pages are positioned  at the top with frontmatter.
- `_category_.yml` are generated in each folder to control category labels and position with pre-defined values. 

Related:

- #216

### CODE REVIEW

**Comment by krailler** [comment]
How can I use the manual sidebar? I don't like the autogenerated sidebar

**Comment by tgreyuk** [comment]
The typedoc sidebar will be autogenerated but you can manually control the rest of the sidebar. See point 2 in https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/docusaurus-plugin-typedoc#sidebar.

**Comment by krailler** [comment]
> The typedoc sidebar will be autogenerated but you can manually control the rest of the sidebar. See point 2 in https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/docusaurus-plugin-typedoc#sidebar.

But `typedoc-sidebar.js` doesn't contains the file list...

**Comment by tgreyuk** [comment]
No - because it is generated by the file system and the end result 'should' be the same. 

What is your use-case for needing the manual sidebar? Is there a particular issue you are having?

**Pull request merged**
